Repository Null-References/Uncertainty, pull requests merged in 2021-07, with the labels that each got.

#47 Health system
  Assets/Prefabs/NPCs/Wasp.prefab
  Assets/Prefabs/Projectiles/simpleProjectile.prefab
  Assets/Scenes/base.unity
  Assets/Scripts/HealthSystem.meta
  Assets/Scripts/HealthSystem/Damage.meta
  Assets/Scripts/HealthSystem/Damage/DamageDealer.meta
  Assets/Scripts/HealthSystem/Damage/DamageDealer/DamageDealer.cs
  Assets/Scripts/HealthSystem/Damage/DamageDealer/DamageDealer.cs.meta
  Assets/Scripts/HealthSystem/Damage/DamageDealer/IDamage.cs
  Assets/Scripts/HealthSystem/Damage/DamageDealer/IDamage.cs.meta
  Assets/Scripts/HealthSystem/Damage/DamageDealer/NormalDamage.cs
  Assets/Scripts/HealthSystem/Damage/DamageDealer/NormalDamage.cs.meta
  Assets/Scripts/HealthSystem/Damage/DamageTaker.meta
  Assets/Scripts/HealthSystem/Damage/DamageTaker/ITakeDamage.cs
  Assets/Scripts/HealthSystem/Damage/DamageTaker/ITakeDamage.cs.meta
  Assets/Scripts/HealthSystem/Damage/DamageTaker/TakeNormalDamage.cs
  Assets/Scripts/HealthSystem/Damage/DamageTaker/TakeNormalDamage.cs.meta
  Assets/Scripts/HealthSystem/Health.meta
  Assets/Scripts/HealthSystem/Health/EnemyHealthAction.cs
  Assets/Scripts/HealthSystem/Health/EnemyHealthAction.cs.meta
  Assets/Scripts/HealthSystem/Health/Health.cs
  Assets/Scripts/HealthSystem/Health/Health.cs.meta
  Assets/Scripts/HealthSystem/Health/PlayerHealthAction.cs
  Assets/Scripts/HealthSystem/Health/PlayerHealthAction.cs.meta
  Assets/Scripts/Weapons/Blaster.cs
  Assets/Scripts/Weapons/Projectile.meta
  Assets/Scripts/Weapons/Projectile/IProjectile.cs
  Assets/Scripts/Weapons/Projectile/IProjectile.cs.meta
  Assets/Scripts/Weapons/Projectile/NormalBullet.cs
  Assets/Scripts/Weapons/Projectile/NormalBullet.cs.meta
  Assets/Scripts/Weapons/Projectile/NormalBulletPool.cs
  Assets/Scripts/Weapons/Projectile/NormalBulletPool.cs.meta
  Assets/Scripts/Weapons/SimpleProjectile.cs
  Assets/Scripts/Weapons/SimpleProjectilePool.cs
  Assets/Scripts/Weapons/Weapon.meta
  Assets/Scripts/Weapons/Weapon/Blaster.cs
  Assets/Scripts/Weapons/Weapon/Blaster.cs.meta
  Assets/Scripts/Weapons/Weapon/WeaponBase.cs
  Assets/Scripts/Weapons/Weapon/WeaponBase.cs.meta
  Assets/UML/Class Diagram/ClassDiagram.cd
  Assets/UML/Class Diagram/ClassDiagram.png
Labels: Features

#50 Sequence diagram Pull Request #37
  Documentation/Project_Scheduling.md
  Documentation/Sequence_Diagram.md
  Documentation/Sequence_Diagram_Pictures/Blaster/Blaster_SetProjectileSettings.png
  Documentation/Sequence_Diagram_Pictures/Blaster/Blaster_Shoot.png
  Documentation/Sequence_Diagram_Pictures/Blaster/Blaster_Start.png
  Documentation/Sequence_Diagram_Pictures/DamageDealer/DamageDealer_Start.png
  Documentation/Sequence_Diagram_Pictures/EnemyAnimationController/EnemyAnimationController_SetIdle.png
  Documentation/Sequence_Diagram_Pictures/EnemyAnimationController/EnemyAnimationController_SetShooting.png
  Documentation/Sequence_Diagram_Pictures/EnemyChase/EnemyChase_ChasePlayer.png
  Documentation/Sequence_Diagram_Pictures/EnemyChase/EnemyChase_GetDependencies.png
  Documentation/Sequence_Diagram_Pictures/EnemyChase/EnemyChase_Start.png
  Documentation/Sequence_Diagram_Pictures/EnemyChase/EnemyChase_Update.png
  Documentation/Sequence_Diagram_Pictures/EnemyIdle/EnemyIdle_Start.png
  Documentation/Sequence_Diagram_Pictures/EnemyIdle/EnemyIdle_Update.png
  Documentation/Sequence_Diagram_Pictures/EnemyPatrol/EnemyPatrol_OnEnable.png
  Documentation/Sequence_Diagram_Pictures/EnemyPatrol/EnemyPatrol_Start.png
  Documentation/Sequence_Diagram_Pictures/EnemyPatrol/EnemyPatrol_Update.png
  Documentation/Sequence_Diagram_Pictures/EnemyWeaponController/EnemyWeaponController_Update.png
  Documentation/Sequence_Diagram_Pictures/GameManager/GameManager_Awake.png
  Documentation/Sequence_Diagram_Pictures/Health/Health_ReduceHealth.png
  Documentation/Sequence_Diagram_Pictures/LookAt/LookAt_Update.png
  Documentation/Sequence_Diagram_Pictures/NonRepeatableTimer/NonRepeatableTimer_Tick.png
  Documentation/Sequence_Diagram_Pictures/PoolBase/PoolBase_Awake.png
  Documentation/Sequence_Diagram_Pictures/PoolBase/PoolBase_Get.png
  Documentation/Sequence_Diagram_Pictures/PoolBase/PoolBase_ReturnToPool.png
  Documentation/Sequence_Diagram_Pictures/ShipControler/ShipControler_FixedUpdate.png
  Documentation/Sequence_Diagram_Pictures/ShipControler/ShipControler_Update.png
  Documentation/Sequence_Diagram_Pictures/TakeNormalDamage/TakeNormalDamage_TakeDamage.png
  README.md
Labels: Analysis & Design, documentation

#54 Save and database
  Assets/Scripts/GameManager.cs
  Assets/Scripts/NPC/WaspBotPool.cs
  Assets/Scripts/SavingAndLoading.meta
  Assets/Scripts/SavingAndLoading/SavingLoadingData.cs
  Assets/Scripts/SavingAndLoading/SavingLoadingData.cs.meta
  Documentation/Project_Scheduling.md
  README.md
Labels: Features, enhancement
